version: "3"
services:
    db:
        image: mongo:6.0.4
        volumes:
          - ./data/db:/data/db
          #- ./data/dump:/dump
        expose:
          - "27017"
        ports:
        - "27017:27017"

    broker:
        image: redis
        volumes:
          - ./data/broker:/data
        expose:
          - "6379"
        ports:
          - "6379:6379"
          
    udata:
        build: .
        #command: serve --reload
        #environment:
        #  - FLASK_DEBUG=true
        volumes:
          - ./udata-fs:/udata/fs
          - .:/src/gouvfr
          - ./udata.cfg:/udata/udata.cfg
          - ./logs:/logs
        environment:
          TZ: "Portugal"
        network_mode: "host"
        healthcheck:
          test: >
            bash -c "
            if nc -z -v -w 3 127.0.0.1 7000; then
              echo 'Connection successful';
              exit 0;
            else
              echo 'Connection failed';
              exit 1;
            fi"
          interval: 5s
          timeout: 3s
          retries: 3
          start_period: 180s
        #ports:
        # - "7000:7000"